CHECKLIST = {
    "version": "1.1",
    "legend": {"support": "0-3", "freq": "F0-F4", "gen": "G0-G3"},
    "areas": [
        {
            "id": "AP",
            "name": "Autonomie personali",
            "items": [
                {"id": "AP01", "label": "Si lava le mani completando la routine funzionale"},
                {"id": "AP02", "label": "Si lava il viso completando l’azione"},
                {"id": "AP03", "label": "Si lava i denti completando la routine prevista"},
                {"id": "AP04", "label": "Indossa e toglie i capi di abbigliamento quotidiani"},
                {"id": "AP05", "label": "Gestisce i sistemi di chiusura dei vestiti"},
                {"id": "AP06", "label": "Gestisce l’allacciamento delle scarpe"},
                {"id": "AP07", "label": "Consuma un pasto utilizzando le posate"},
                {"id": "AP08", "label": "Taglia il cibo con posate in modo funzionale"},
                {"id": "AP09", "label": "Gestisce tovagliolo e pulizia personale durante il pasto"},
                {"id": "AP10", "label": "Beve utilizzando il bicchiere senza rovesciare il contenuto"},
                {"id": "AP11", "label": "Utilizza il fazzoletto per soffiarsi il naso"},
                {"id": "AP12", "label": "Gestisce l’igiene dopo l’uso dei servizi igienici"},
            ],
        },
        {
            "id": "GT",
            "name": "Gestione del tempo",
            "items": [
                {"id": "GT01", "label": "Avvia un’attività all’orario stabilito"},
                {"id": "GT02", "label": "Conclude un’attività entro il tempo previsto"},
                {"id": "GT03", "label": "Passa da un’attività a un’altra rispettando la consegna temporale"},
                {"id": "GT04", "label": "Segue una routine giornaliera strutturata"},
                {"id": "GT05", "label": "Utilizza un supporto temporale per orientarsi nella giornata"},
                {"id": "GT06", "label": "Legge l’orologio per orientarsi nel tempo"},
                {"id": "GT07", "label": "Attende un turno o un evento rispettando il tempo indicato"},
                {"id": "GT08", "label": "Gestisce un breve tempo libero senza disorganizzarsi"},
            ],
        },
        {
            "id": "GD",
            "name": "Gestione del denaro",
            "items": [
                {"id": "GD01", "label": "Riconosce monete e banconote di uso comune"},
                {"id": "GD02", "label": "Associa il denaro al valore richiesto per un acquisto semplice"},
                {"id": "GD03", "label": "Effettua un pagamento in contanti per un acquisto semplice"},
                {"id": "GD04", "label": "Riceve e controlla il resto dopo un pagamento"},
                {"id": "GD05", "label": "Conserva il denaro in modo adeguato durante l’attività"},
                {"id": "GD06", "label": "Rispetta un limite di spesa indicato"},
                {"id": "GD07", "label": "Riconosce la necessità di pagare per ottenere un bene o servizio"},
            ],
        },
        {
            "id": "GA",
            "name": "Gestione dell’ambiente",
            "items": [
                {"id": "GA01", "label": "Riordina il proprio spazio personale dopo l’attività"},
                {"id": "GA02", "label": "Ripone gli oggetti personali nel luogo previsto"},
                {"id": "GA03", "label": "Utilizza correttamente gli oggetti in base alla loro funzione"},
                {"id": "GA04", "label": "Restituisce gli oggetti condivisi al termine dell’uso"},
                {"id": "GA05", "label": "Rispetta le regole di utilizzo degli spazi comuni"},
                {"id": "GA06", "label": "Mantiene in ordine uno spazio comune dopo l’attività"},
                {"id": "GA07", "label": "Si muove negli ambienti rispettando i percorsi indicati"},
            ],
        },
        {
            "id": "AD",
            "name": "Autonomie domestiche",
            "items": [
                {"id": "AD01", "label": "Prepara uno spuntino semplice seguendo i passaggi essenziali"},
                {"id": "AD02", "label": "Apparecchia la tavola per un pasto semplice"},
                {"id": "AD03", "label": "Sparecchia la tavola al termine del pasto"},
                {"id": "AD04", "label": "Lava stoviglie utilizzando acqua e detergente"},
                {"id": "AD05", "label": "Pulisce una superficie dopo l’attività"},
                {"id": "AD06", "label": "Utilizza un elettrodomestico semplice in modo sicuro"},
                {"id": "AD07", "label": "Ripone il bucato pulito nel luogo previsto"},
            ],
        },
        {
            "id": "AS",
            "name": "Autonomie sociali",
            "items": [
                {"id": "AS01", "label": "Chiede aiuto in modo comprensibile quando necessario"},
                {"id": "AS02", "label": "Esprime un bisogno o una richiesta in modo funzionale"},
                {"id": "AS03", "label": "Rispetta il turno durante un’attività condivisa"},
                {"id": "AS04", "label": "Segue una regola sociale esplicita indicata dall’adulto"},
                {"id": "AS05", "label": "Avvia un’interazione sociale semplice con un pari o un adulto"},
                {"id": "AS06", "label": "Mantiene un’interazione sociale semplice fino alla conclusione"},
                {"id": "AS07", "label": "Accetta una richiesta o un limite comunicato dall’adulto"},
            ],
        },
        {
            "id": "AL",
            "name": "Apprendimento",
            "items": [
                {"id": "AL01", "label": "Mantiene l’attenzione su un compito strutturato"},
                {"id": "AL02", "label": "Comprende una consegna semplice"},
                {"id": "AL03", "label": "Segue una consegna composta da più passaggi"},
                {"id": "AL04", "label": "Riconosce lettere o simboli di uso frequente"},
                {"id": "AL05", "label": "Legge parole o brevi frasi in modo funzionale"},
                {"id": "AL06", "label": "Scrive parole o brevi frasi in modo funzionale"},
                {"id": "AL07", "label": "Esegue semplici operazioni o conteggi funzionali"},
                {"id": "AL08", "label": "Utilizza strategie apprese per risolvere un compito noto"},
            ],
        },
    ],
}
